### ISSUE TITLE
Setup command does not exist

### ISSUE THREAD

**Issue by lemz1** [CobaltBar/HxPKG#2]
when doing `haxelib --global install hxpkg`
the setup command doesn't exist

however if i do
`haxelib --global git hxpkg https://github.com/CobaltBar/HxPKG`
i can run the setup command

i dont exactly know how haxe libraries work, but i guess you need to update the 'official' haxelib, so that the setup command exists

**Comment by CobaltBar** [comment]
Yea, i haven't released 1.5.0 yet so you have to use git hxpkg

**Comment by CobaltBar** [comment]
there, i published it on haxelib
its good now
